Repository kostua16/TLT_NC_AMA_2021, pull requests merged in 2022-04, with the labels that each got.

#100 DONE: feat(ComplaintHandlingService): Feign client для ComplaintHandlingService #93
  projects/hotel_automation_project/common/pom.xml
  projects/hotel_automation_project/common/src/main/java/nc/unc/ama/complaint_handling_service/dto/ComplaintDTO.java
  projects/hotel_automation_project/common/src/main/java/nc/unc/ama/complaint_handling_service/dto/ComplaintREST.java
  projects/hotel_automation_project/common/src/main/java/nc/unc/ama/complaint_handling_service/dto/GuestREST.java
  projects/hotel_automation_project/common/src/main/java/nc/unc/ama/complaint_handling_service/dto/OccupiedRoomsREST.java
  projects/hotel_automation_project/common/src/main/java/nc/unc/ama/complaint_handling_service/dto/StaffMemberREST.java
  projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/controllers/ComplaintController.java
  projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/controllers/GuestControllerImpl.java
  projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/controllers/RatingControllerImpl.java
  projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/entities/Complaint.java
  projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/repositories/ComplaintRepo.java
  projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/services/ComplaintService.java
  projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/services/StaffRatingService.java
  projects/hotel_automation_project/complaint_handling_service/src/main/resources/application.yml
  projects/hotel_automation_project/complaint_handling_service/src/test/java/nc/unc/ama/complaint_handling_service/ComplaintHandlingServiceApplicationTests.java
Labels: build_passed

#80 DONE: feat: Новый модуль Booking Service для задачи #54
  projects/hotel_automation_project/booking_service/pom.xml
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/BookingServiceApplication.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/controllers/GuestControllerImpl.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/controllers/OccupiedRoomsController.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/controllers/PaymentControllerImpl.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/controllers/RegistrationController.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/entities/OccupiedRooms.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/entities/Registration.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/repositories/OccupiedRoomsRepo.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/repositories/RegistrationRepo.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/OccupiedRoomsService.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/RegistrationService.java
Labels: build_passed

#70 WIP: Features/security updates
  .github/workflows/build.yml
  pom.xml
  projects/Web_Bank_tomcat/pom.xml
  projects/hotel_automation_project/staff_service/pom.xml
  projects/test_jsf/pom.xml
Labels: dependencies, build_failed

#28 WIP: Featues/issue #26
  projects/BankServlet/pom.xml
  projects/BankServlet/src/main/java/com/example/bankservlet/AuthUser.java
  projects/BankServlet/src/main/java/com/example/bankservlet/RegUser.java
  projects/BankServlet/src/main/java/com/example/bankservlet/User.java
  projects/BankServlet/src/main/webapp/DownB.jsp
  projects/BankServlet/src/main/webapp/UpB.jsp
  projects/BankServlet/src/main/webapp/User.jsp
  projects/BankServlet/src/main/webapp/WEB-INF/web.xml
  projects/BankServlet/src/main/webapp/Wrong.jsp
  projects/BankServlet/src/main/webapp/auth.jsp
  projects/BankServlet/src/main/webapp/index.jsp
  projects/BankServlet/src/main/webapp/registration.jsp
  projects/BankServlet/src/main/webapp/stop.jsp
  projects/pom.xml
Labels: build_failed

#46 WIP: feat: Новый модуль для задачи #45
  projects/banksystem/.mvn/wrapper/maven-wrapper.properties
  projects/banksystem/HELP.md
  projects/banksystem/mvnw
  projects/banksystem/mvnw.cmd
  projects/banksystem/pom.xml
  projects/banksystem/src/main/java/com/example/banksystem/BanksystemApplication.java
  projects/banksystem/src/main/java/com/example/banksystem/controller/BankController.java
  projects/banksystem/src/main/java/com/example/banksystem/controller/BankomatController.java
  projects/banksystem/src/main/java/com/example/banksystem/model/Client.java
  projects/banksystem/src/main/java/com/example/banksystem/service/Bank.java
  projects/banksystem/src/main/java/com/example/banksystem/service/Bankomat.java
  projects/banksystem/src/main/resources/application.properties
  projects/banksystem/src/test/java/com/example/banksystem/BanksystemApplicationTests.java
  projects/banksystem/test.http
Labels: build_failed

#21 WIP: 'ДЗ'
  HW.sql
  Банк/src/com/company/Bank.java
  Банк/src/com/company/Bankomat.java
  Банк/src/com/company/Client.java
  Банк/src/com/company/Main.java
Labels: build_failed

#75 DONE: Feature/simple spring app
  projects/test_spring_app/.gitignore
  projects/test_spring_app/pom.xml
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/TestSpringAppApplication.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/config/WebSecurityConfig.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/controllers/AuthController.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/controllers/AuthRestController.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/controllers/ExceptionController.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/dto/UserInfoDTO.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/entities/UserInfo.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/repositories/UserInfoRepository.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/services/AuthService.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/services/SecurityService.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/services/SecurityServiceImpl.java
  projects/test_spring_app/src/main/java/nc/unc/ama/test_spring_app/services/UserDetailsServiceImpl.java
  projects/test_spring_app/src/main/resources/application.yml
  projects/test_spring_app/src/main/resources/static/css/main.css
  projects/test_spring_app/src/main/resources/templates/login.html
  projects/test_spring_app/src/main/resources/templates/registration.html
  projects/test_spring_app/src/main/resources/templates/welcome.html
Labels: build_passed

#135 DONE: feat(BookingService): Room контролеры, сервисы, репозиторий, entity, DTO #132
  projects/hotel_automation_project/booking_service/pom.xml
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/controllers/OccupiedRoomsController.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/controllers/RoomsController.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/entities/HotelRoom.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/entities/OccupiedRooms.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/repositories/RoomsRepo.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/OccupiedRoomsService.java
  projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/RoomsService.java
  projects/hotel_automation_project/common/src/main/java/nc/unc/ama/complaint_handling_service/dto/HotelRoomDTO.java
  projects/hotel_automation_project/pom.xml
Labels: build_passed
